### ISSUE TITLE
Login button should be center.

### ISSUE THREAD

**Issue by ronisarkarexe** [ronisarkarexe/PMSPlatform#2]
Login button should be center.

**Comment by sau-sal** [comment]
![btnCenter](https://github.com/ronisarkarexe/PMSPlatform/assets/71603691/e42d1588-b080-4c67-ac08-d50c4272d2cb)

![btnCenter2](https://github.com/ronisarkarexe/PMSPlatform/assets/71603691/a39ebb32-e7af-4129-931a-281932e30c74)

I have attached two images. Please let me know which one you are looking for.

**Comment by sau-sal** [comment]
Please assign this issue to me.

**Comment by ronisarkarexe** [comment]
> ![btnCenter](https://user-images.githubusercontent.com/71603691/280241212-e42d1588-b080-4c67-ac08-d50c4272d2cb.png)
> 
> ![btnCenter2](https://user-images.githubusercontent.com/71603691/280242030-a39ebb32-e7af-4129-931a-281932e30c74.png)
> 
> I have attached two images. Please let me know which one you are looking for.

first one good for me, assign it to you.

**Comment by ronisarkarexe** [comment]
@sau-sal Before creating a pull request, fork this project, create a branch and then push the changes to your new branch. please follow this

**Comment by ronisarkarexe** [comment]
@sau-sal thanks for your interest.
